USE todo;

CREATE TABLE TASK (
  ID          INT           AUTO_INCREMENT,
  VERSION     INT           NOT NULL,
  UUID        BINARY(16)    NOT NULL,
  CREATED_AT  TIMESTAMP     NOT NULL,
  MODIFIED_AT TIMESTAMP     NOT NULL,
  TITLE       VARCHAR(256)  NOT NULL,
  DESCRIPTION VARCHAR(1024) DEFAULT NULL,
  FINISHED_AT TIMESTAMP     DEFAULT NULL,
  ARCHIVED_AT TIMESTAMP     DEFAULT NULL,
  CONSTRAINT  PK_TASK       PRIMARY KEY(ID),
  CONSTRAINT  UQ_TASK_UUID  UNIQUE(UUID)
) ENGINE=INNODB AUTO_INCREMENT=100 CHARACTER SET utf32 COLLATE utf32_general_ci;

CREATE TABLE TAG (
  ID          INT           AUTO_INCREMENT,
  VERSION     INT           NOT NULL,
  UUID        BINARY(16)    NOT NULL,
  CREATED_AT  TIMESTAMP     NOT NULL,
  `NAME`      VARCHAR(256)  NOT NULL,
  DESCRIPTION VARCHAR(1024) DEFAULT NULL,
  CONSTRAINT  PK_TAG        PRIMARY KEY(ID),
  CONSTRAINT  UQ_TAG_UUID   UNIQUE(UUID),
  CONSTRAINT  UQ_TAG_NAME   UNIQUE(`NAME`)
) ENGINE=INNODB AUTO_INCREMENT=100 CHARACTER SET utf32 COLLATE utf32_general_ci;

CREATE TABLE TASK_TAG (
  TASK_ID     INT              NOT NULL,
  TAG_ID      INT              NOT NULL
--   CONSTRAINT  FK_TASK_TAG_TASK FOREIGN KEY (TASK_ID) REFERENCES TASK(ID),
--   CONSTRAINT  FK_TASK_TAG_TAG  FOREIGN KEY (TAG_ID)  REFERENCES TAG(ID)
) ENGINE=INNODB CHARACTER SET utf32 COLLATE utf32_general_ci;